name: tim.kremer
favicon: null
layout_spectrum: 0.650376
typography_spectrum: 0.8215836531016976
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: Tour Divide July 2016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D3DFEF'
    - '#272F31'
    - '#8197C0'
    - '#FFFFFF'
    - '#6D6D37'
  brandStrength: 0.1145226324442774
  lightness: 0.5625
  saturation: 0.6388271155301481
  rhythmicContrast: 0.2723058480769396
purpose: []
